#!/bin/bash
#
#    Copyright 2016 Iron City Software LLC
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
#
# Roundtrips a Garmin NavData file to a proto and back.
# If the starting and ending files are the same, the encoding and decoding
# are lossless.
set -e
CANONICAL_GARMIN_FILE=$1
if [[ -z "$CANONICAL_GARMIN_FILE" ]] ; then
  echo "Usage: $0 [canonical Garmin Navdata file]"
  exit -1
fi
if [[ ! -f $CANONICAL_GARMIN_FILE ]] ; then
  echo "$CANONICAL_GARMIN_FILE does not exist"
  exit -1
fi
PROTO_FILE=/tmp/proto.bin
GARMIN_FILE=/tmp/garmin.bin
scripts/NavDataTool decode $CANONICAL_GARMIN_FILE $PROTO_FILE
scripts/NavDataTool encode $PROTO_FILE $GARMIN_FILE
if cmp -s "$GARMIN_FILE" "$CANONICAL_GARMIN_FILE" ; then
  echo "SUCCESS"
else
  echo "FAIL:  Navdata files are different.  Possibly helpful commands:"
  echo "vimdiff <(xxd $CANONICAL_GARMIN_FILE) <(xxd $GARMIN_FILE)"
  echo "scripts/PrintProto $PROTO_FILE"
fi
